### ISSUE TITLE
folders do not appear the same as screen shot

### ISSUE THREAD

**Issue by cole-gillespie** [jrnewell/predawn-twilight-theme#1]
i am a bit confused on how to get my folders and files to look the same as yours

**Comment by jrnewell** [comment]
Hi Cole,

You actually need to install 2 sublime packages: 'Predawn' and 'Predawn Twilight Theme'.
1.  First, make sure you have the latest ([Sublime Text 3](http://www.sublimetext.com/3)) build, so you get the icons in the sidebar
2. Install sublime package 'Predawn'
3. Bring up your 'user preferences'.  I use these predawn settings
   
   ```
      "theme": "predawn-DEV.sublime-theme",
      "findreplace_small": true,
      "tabs_medium": true,
   ```
4. Restart sublime text
5. Install 'Predawn Twilight Theme' package
6. Activate predawn twilight theme
   
   ```
      Preferences -> Color Scheme -> Predawn Twilight Theme -> Predawn Twilight
   ```
   
   Or alternatively, you can add this line to your 'user preferences'
   
   ```
   "color_scheme": "Packages/Predawn Twilight Theme/Predawn Twilight.tmTheme",
   ```

I hope that helps!
